# schema with the same name servers 
schemaname1 = "siis"

schemaname2 = "siistesting"

[servers]
  # You can indent as you please. Tabs or spaces. TOML don't care.
  [servers.1]
  host = "127.0.0.1"
  port = "3306"
  user = "root"
  password = "jose1"
  name = "siis"

  [servers.2]
  host = "127.0.0.1"
  port = "3306"
  user = "root"
  password = "jose1"
  name = "siistesting"