# schema with the same name servers 
schemaname1 = "siis"

schemaname2 = "siistesting"

[servers]
  # You can indent as you please. Tabs or spaces. TOML don't care.
  [servers.1]
  host = "siistesting.c36dahs0arhc.us-east-1.rds.amazonaws.com"
  port = "3306"
  user = "admin"
  password = "NI0zv26k8uRXoo7VgIdo"
  name = "siis"

  [servers.2]
  host = "siistesting.c36dahs0arhc.us-east-1.rds.amazonaws.com"
  port = "3306"
  user = "admin"
  password = "NI0zv26k8uRXoo7VgIdo"
  name = "siistesting"